# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UserInfoWindow(object):
    def setupUi(self, UserInfoWindow):
        UserInfoWindow.setObjectName("UserInfoWindow")
        UserInfoWindow.resize(380, 520)
        self.centralwidget = QtWidgets.QWidget(UserInfoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_user = QtWidgets.QHBoxLayout()
        self.horizontalLayout_user.setSpacing(15)
        self.horizontalLayout_user.setObjectName("horizontalLayout_user")
        self.label_avatar = QtWidgets.QLabel(self.centralwidget)
        self.label_avatar.setMinimumSize(QtCore.QSize(80, 80))
        self.label_avatar.setMaximumSize(QtCore.QSize(80, 80))
        self.label_avatar.setScaledContents(True)
        self.label_avatar.setObjectName("label_avatar")
        self.horizontalLayout_user.addWidget(self.label_avatar)
        self.label_nickname = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_nickname.setFont(font)
        self.label_nickname.setObjectName("label_nickname")
        self.horizontalLayout_user.addWidget(self.label_nickname)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_user.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_user)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setProperty("orientation", 4)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_title = QtWidgets.QHBoxLayout()
        self.horizontalLayout_title.setObjectName("horizontalLayout_title")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_title.addWidget(self.label_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_title.addItem(spacerItem1)
        self.btn_today_rec = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btn_today_rec.setFont(font)
        self.btn_today_rec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_today_rec.setObjectName("btn_today_rec")
        self.horizontalLayout_title.addWidget(self.btn_today_rec)
        self.btn_history_rec = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.btn_history_rec.setFont(font)
        self.btn_history_rec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_history_rec.setObjectName("btn_history_rec")
        self.horizontalLayout_title.addWidget(self.btn_history_rec)
        self.verticalLayout.addLayout(self.horizontalLayout_title)
        self.listWidget_playlists = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.listWidget_playlists.setFont(font)
        self.listWidget_playlists.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.listWidget_playlists.setObjectName("listWidget_playlists")
        self.verticalLayout.addWidget(self.listWidget_playlists)
        UserInfoWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserInfoWindow)
        QtCore.QMetaObject.connectSlotsByName(UserInfoWindow)

    def retranslateUi(self, UserInfoWindow):
        _translate = QtCore.QCoreApplication.translate
        UserInfoWindow.setWindowTitle(_translate("UserInfoWindow", "我的音乐空间"))
        self.label_avatar.setText(_translate("UserInfoWindow", "头像"))
        self.label_nickname.setText(_translate("UserInfoWindow", "未登录用户"))
        self.label_title.setText(_translate("UserInfoWindow", "我的歌单"))
        self.btn_today_rec.setText(_translate("UserInfoWindow", "🌟 今日推荐"))
        self.btn_history_rec.setText(_translate("UserInfoWindow", "🕒 获取历史..."))
